"""02_add_deleted_field

Revision ID: 899393743856
Revises: 73c03306d384
Create Date: 2023-12-20 22:32:29.882136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '899393743856'
down_revision: Union[str, None] = '73c03306d384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.drop_column('url', 'call_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url', sa.Column('call_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('url', 'deleted')
    # ### end Alembic commands ###
