"""04_add_url_field_and_constraints

Revision ID: f5f3c83d306d
Revises: eb9469f870f1
Create Date: 2023-12-25 22:14:03.969132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5f3c83d306d'
down_revision: Union[str, None] = 'eb9469f870f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url', sa.Column('url_type', sa.String(), nullable=False))
    op.drop_constraint('url_original_url_key', 'url', type_='unique')
    op.create_unique_constraint('original_url_user_id_constraint', 'url', ['original_url', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('original_url_user_id_constraint', 'url', type_='unique')
    op.create_unique_constraint('url_original_url_key', 'url', ['original_url'])
    op.drop_column('url', 'url_type')
    # ### end Alembic commands ###
